### ISSUE TITLE
spring-boot-tutorial 里面link 没有更新。

### ISSUE THREAD

**Issue by weigoxp** [dunwu/spring-boot-tutorial#4]
https://dunwu.github.io/spring-boot-tutorial/#/

codes 目录里文件移动到subfolder， link没有更新。

**Comment by dunwu** [comment]
> https://dunwu.github.io/spring-boot-tutorial/#/
> 
> codes 目录里文件移动到subfolder， link没有更新。

抱歉，刚看到 issue。已修正，谢谢提醒
